# Generated by Django 4.1.5 on 2023-03-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='tax',
        ),
    ]
