# Generated by Django 4.1.5 on 2023-03-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmaceuticl',
            name='isAvailable',
            field=models.BooleanField(default=False),
        ),
    ]
