# Generated by Django 4.1.5 on 2023-03-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='patient',
        ),
        migrations.AddField(
            model_name='bill',
            name='patient',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='Hospital.patient'),
        ),
    ]
