# Generated by Django 4.1.5 on 2023-03-15 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='report',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='tests',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.report'),
        ),
    ]
