# Generated by Django 4.1.5 on 2023-03-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='salary',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
