# Generated by Django 4.1.5 on 2023-03-15 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_remove_report_doctor_remove_report_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[('blood count', 'blood count'), ('blood typing', 'blood typing'), ('glucose tolerance test', 'glucose tolerance test'), ('thymol turbidity', 'thymol turbidity'), ('liver function test', 'liver function test'), ('kidney function test', 'kidney function test'), ('lumbar puncture', 'lumbar puncture'), ('toxicology test', 'toxicology test'), ('angiocardiography', 'angiocardiography'), ('cholecystography', 'cholecystography'), ('ECG', 'ECG'), ('X-ray', 'X-ray')], max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='doctor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.doctor'),
        ),
        migrations.AddField(
            model_name='report',
            name='patient',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tests',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.test'),
        ),
        migrations.AlterField(
            model_name='report',
            name='test_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.test'),
        ),
    ]
