# Generated by Django 4.1.5 on 2023-03-06 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_alter_doctor_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='room_no',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.room'),
        ),
    ]
