# Generated by Django 4.2 on 2023-09-22 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_remove_patient_address_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='start',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
