# Generated by Django 4.1.5 on 2023-04-06 18:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_remove_bill_patient_bill_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hour', models.CharField(max_length=1)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Presence', models.BooleanField(default=False)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.doctor')),
            ],
        ),
    ]
