# Generated by Django 4.1.5 on 2023-03-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
