# Generated by Django 4.1.5 on 2023-04-06 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.doctor'),
        ),
    ]
